# Generated by Django 2.1.7 on 2019-03-28 21:10

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to=blog.utils.post_image_file_path),
        ),
    ]
